fixtures:
  repositories:
    stdlib: git://github.com/puppetlabs/puppetlabs-stdlib.git
    vcsrepo: git://github.com/puppetlabs/puppetlabs-vcsrepo.git
    inifil: git://github.com/puppetlabs/puppetlabs-inifile.git
  symlinks:
    nagdash: "#{source_dir}"
